# Generated by Django 6.1 on 2026-08-08 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('badge_text', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('image_url', models.CharField(blank=True, default='', help_text='Fallback static image path if file not uploaded', max_length=500)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.CharField(default='#products', max_length=255)),
                ('banner_type', models.CharField(choices=[('hero', 'Hero Banner'), ('promo', 'Promotional Banner'), ('side', 'Side Banner')], default='hero', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
