# Generated by Django 6.1 on 2026-08-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='Fallback static image URL/path', max_length=500),
        ),
    ]
