# Generated by Django 6.1 on 2026-08-08 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=100)),
                ('city', models.CharField(default='Dhaka', max_length=100)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=60.0, max_digits=8)),
                ('estimated_delivery_time', models.CharField(default='30-45 mins', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'db_table': 'delivery_zones',
                'ordering': ['area_name'],
            },
        ),
    ]
